# Data paths and options when using EleutherAI cluster
{
  "data-path": "/mnt/ssd-1/data/enwik8/enwik8/enwik8_text_document",
  "vocab-file": "/mnt/ssd-1/data/gpt2-vocab.json",
  "merge-file": "/mnt/ssd-1/data/gpt2-merges.txt",
  "save": "/mnt/ssd-cluster/checkpoints/",
  "load": "/mnt/ssd-cluster/checkpoints/",
  "tensorboard-dir": "/mnt/ssd-cluster/tensorboard",
  "log-dir": "/mnt/ssd-cluster/logs",
  "wandb_team": "eleutherai",
  "wandb_group": "rope"
}
